select pg_catalog.jsonb_build_object(
 'owner',pg_catalog.pg_get_userbyid(c.relowner),'kind',c.relkind,
 'ownerRole',(select pg_catalog.jsonb_build_object('super',r.rolsuper,'inherit',r.rolinherit,'createRole',r.rolcreaterole,'createDb',r.rolcreatedb,'login',r.rolcanlogin,'bypassRls',r.rolbypassrls) from pg_catalog.pg_roles r where r.oid=c.relowner),
 'acl',(select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('grantor',pg_catalog.pg_get_userbyid(a.grantor),'grantee',case when a.grantee=0 then 'PUBLIC' else pg_catalog.pg_get_userbyid(a.grantee) end,'privilege',a.privilege_type,'grantable',a.is_grantable) order by a.grantor::regrole::text,a.grantee::regrole::text,a.privilege_type),'[]'::jsonb) from pg_catalog.aclexplode(coalesce(c.relacl,pg_catalog.acldefault('r',c.relowner))) a),
 'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,
 'columns',(select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('name',a.attname,'type',pg_catalog.format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'default',pg_catalog.pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by a.attnum)
  from pg_catalog.pg_attribute a left join pg_catalog.pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
 'constraints',(select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('name',x.conname,'type',x.contype,'definition',pg_catalog.pg_get_constraintdef(x.oid),'validated',x.convalidated) order by x.conname),'[]'::jsonb) from pg_catalog.pg_constraint x where x.conrelid=c.oid and x.conname<>'accounts153_owned_writer_inactive'),
 'indexes',(select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('name',idx.relname,'definition',pg_catalog.pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready) order by idx.relname),'[]'::jsonb) from pg_catalog.pg_index i join pg_catalog.pg_class idx on idx.oid=i.indexrelid where i.indrelid=c.oid),
 'policies',(select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('name',p.polname,'roles',(select pg_catalog.jsonb_agg(case when role_oid=0 then 'PUBLIC' else pg_catalog.pg_get_userbyid(role_oid) end order by case when role_oid=0 then 'PUBLIC' else pg_catalog.pg_get_userbyid(role_oid) end) from pg_catalog.unnest(p.polroles) role_oid),'command',p.polcmd,'permissive',p.polpermissive,'using',pg_catalog.pg_get_expr(p.polqual,p.polrelid),'check',pg_catalog.pg_get_expr(p.polwithcheck,p.polrelid)) order by p.polname),'[]'::jsonb) from pg_catalog.pg_policy p where p.polrelid=c.oid),
 'triggers',(select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('name',t.tgname,'definition',pg_catalog.pg_get_triggerdef(t.oid),'enabled',t.tgenabled) order by t.tgname),'[]'::jsonb) from pg_catalog.pg_trigger t where t.tgrelid=c.oid and not t.tgisinternal))
from pg_catalog.pg_class c where c.oid=pg_catalog.to_regclass(%s);
